#!/usr/bin/env node
process.env.NODE_ENV = process.env.NODE_ENV || "production";
require("dotenv").config();

const argv = require("yargs")
  .help("h")
  .alias("h", "help")
  .example("$0", "lookup users that stars")
  .count("verbose")
  .alias("verbose", "v")
  .describe("verbose", "show steps")
  .usage("Usage: $0").argv;

const dir = process.env.NODE_ENV === "development" ? "src" : "dist";
require(`./${dir}/stargazers`)
  .cmd(argv)
  .then(
    () => {
      process.exit(0);
    },
    (error) => {
      console.error(`ERROR! ${error}`);
      process.exit(1);
    }
  );
